### ISSUE TITLE
我在FriendlyDesktop18.04上直接用V4L2读相机，为什么非常卡

### ISSUE THREAD

**Issue by sychaichangkun** [friendlyarm/rk3399-opencv-uvccamera-cpp-demo#1]
你好，
我安装了FriendlyDesktop18.04系统，从网上找的V4L2的源码
双MIPI相机
用v4l2-ctl看到的相机capabilities只有V4L2_CAP_VIDEO_CAPTURE_MPLANE
取到图像的速度很慢很卡，颜色也不对

**Comment by friendlyarm** [comment]
刚更新了代码，你用MJPG方式打开摄像头试试
